trigger: none

pool: infracreation

stages:
  - stage: 
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
<<<<<<< HEAD
              backendServiceArm: 'xyz'
=======
              backendServiceArm: 'infra_creation'
>>>>>>> fc24498 (updated code)
              backendAzureRmStorageAccountName: 'testpipeline117'
              backendAzureRmContainerName: 'xyz'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'infra_creation'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'infra_creation'
          

